version: '3'
services:


  redis-storage:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: no
    ports:
      - "6379:6379"
    expose:
      - "6379"


  aiohttp:
    # Путь до Dockerfile
    build: ./app
    # Имя для создаваемого контейнера
    container_name: backend-aiohttp
    # Создание переменных окружения в контейнере

    env_file:
      - variables.env
      ##
    # Перезапускаем сервис в случае падения 
    restart: no
    extra_hosts:
    - "host.docker.internal:host-gateway"
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./database/tgbot_database.db:/database
      - ./database/bot_log.log:/database
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "8443:8443"
    command: python -u main.py


  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  frps:
    build: ./frp-server
    container_name: frp-server
    restart: no
    ports:
      - "7000:7000"
    expose:
      - "7000"


  

